[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"

[".config/zsh/antigen.zsh"]
  type = "file"
  url = "https://github.com/zsh-users/antigen/releases/latest/download/antigen.zsh"
  refreshPeriod = "168h"

[".asdf"]
  type = "archive"
  url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.13.1.tar.gz"
  stripComponents = 1
